 source 'https://rubygems.org'

 gem 'sinatra'
 #gem 'net-ldap'
 gem 'whenever'
 gem 'rest-client'
 gem 'sinatra-contrib'
 gem 'activesupport'
 #gem 'dm-core'
 #gem 'dm-migrations'
 #gem 'dm-sqlite-adapter'
 #gem 'dm-validations'
 #gem 'attr_encrypted'
