 source 'https://rubygems.org'

 gem 'sinatra'
 #gem 'net-ldap'
 gem 'whenever'
 gem 'rest-client'
 gem 'sinatra-contrib'
 gem 'activesupport'
 gem 'thin'
 gem 'ruby-debug-ide'
 #gem 'ruby-debug-base' #Não é necessário para debugar

 gem 'dm-core'
 gem 'dm-migrations'
 gem 'dm-sqlite-adapter'
 gem 'dm-validations'
 gem 'dm-timestamps'
 gem 'attr_encrypted'
 gem 'test-unit'
 gem 'debase'
 gem 'json'