#!/usr/bin/env ruby

#require_relative '../app'

#Dir.glob('./{../models}/*.rb').each {|file|
# puts(file)
# require_relative file
#}


require_relative '../models/connection'

if ENV['APP_ENVIRONMENT'] == 'production'
  DataMapper.setup(:default, "sqlite3://#{File.expand_path(File.join(File.dirname(__FILE__), "..","production.db"))}")
elsif ENV['APP_ENVIRONMENT'] == 'test'
  DataMapper.setup(:default, "sqlite3://#{File.expand_path(File.join(File.dirname(__FILE__), "..","production.db"))}")
else
  DataMapper.setup(:default, "sqlite3://#{File.expand_path(File.join(File.dirname(__FILE__), "..","production.db"))}")
end

eval(ARGV[2])